### ISSUE TITLE
Cannot read lines from source file in Jar under JRuby

### ISSUE THREAD

**Issue by gfowley** [rocky/linecache#4]
In JRuby source files may be contained in a jar file. These source files may be specified with a nested URL of the form jar:file:/path/to/containing.jar!/path/to/source.rb. JRuby handles such URLs transparently.

Linecache reads a source file twice, using IO#rewind between passes. IO#rewind does not work properly for a file in a jar, resulting in linecache failing to retrieve source lines for the debugger.

**Comment by rocky** [comment]
Patches would be welcome. Thanks.

**Comment by gfowley** [comment]
Thanks for picking this up so quickly.
Do you intend to push a patch or pre-release gem ?
If it helps, I can build the java gem and attach it to a release on my fork, let me know your versioning preference.

**Comment by rocky** [comment]
Yes, please make a java gem. The next version will probably be called 1.3.1. Will review things over the weekend. Thanks.

**Comment by gfowley** [comment]
Done. It's at: https://github.com/gfowley/linecache/releases/tag/1.3.1.pre

Also, PR with matching version bump.

**Comment by rocky** [comment]
I have made what I think hope are the final changes to the master branch to bring it in line with the other branches. Please review this and update your code and PR again. 

Linecache is a big mess. The root cause I think was a lack of runtime support in Ruby for a long while to really support this well.  The master branch only handles Ruby 1.8 and jruby.  Other branches handle versions of Ruby that I don't think most people will use. So you probably want to seek out and find the various other forks of this code and get your changes in that if need be. Sorry for all of the mess.

**Comment by gfowley** [comment]
1.3.1 looks good in JRuby.
New Java gem is at: https://github.com/gfowley/linecache/releases/tag/1.3.1

My change was for an issue that only occurs in JRuby, no need to cause trouble for it in branches that don't support JRuby. 

What mess ? ...supporting multiple versions of Ruby, over such a long period of time is bound to get complicated. As a user of an alternative Ruby (JRuby) on a niche platform (Ruboto/Android) I specially appreciate your work.

**Comment by rocky** [comment]
Java gem should now be on gemcutter. Please close issue after verifying that things work as expected. Thanks for all the help.

**Comment by gfowley** [comment]
Looks good.
Thanks.
